SELECT DISTINCT PRODUCT.ware 
FROM PRODUCT 
JOIN MATERIAL ON PRODUCT.RECIPE_ID = MATERIAL.RECIPE_ID 
JOIN CATEGORY ON MATERIAL.ware = CATEGORY.ware 
WHERE CATEGORY.CLASS = 'Mineral' 
ORDER BY PRODUCT.ware ASC;