SELECT DISTINCT MANUFACTURER.company, PRODUCT.ware 
FROM MANUFACTURER 
JOIN CATEGORY ON PRODUCT.ware = CATEGORY.ware 
JOIN PRODUCT ON MANUFACTURER.RECIPE_ID = PRODUCT.RECIPE_ID 
WHERE CATEGORY.CLASS = 'Raw food' 
ORDER BY PRODUCT.ware ASC, MANUFACTURER.company ASC;
