SELECT DISTINCT m1.COMPANY, p1.WARE, p2.WARE 
FROM MANUFACTURER m1
INNER JOIN PRODUCT p1 ON p1.RECIPE_ID = m1.RECIPE_ID
JOIN CATEGORY c1 ON p1.ware = c1.ware
JOIN MANUFACTURER m2 ON m2.COMPANY = m1.COMPANY
INNER JOIN PRODUCT p2 on p2.RECIPE_ID = m2.RECIPE_ID
JOIN CATEGORY c2 on c2.WARE = p2.WARE
WHERE c2.CLASS = 'Food' and c1.CLASS = 'Fuel';
