SELECT DISTINCT MANUFACTURER.company 
FROM MANUFACTURER 
JOIN PRODUCT ON MANUFACTURER.RECIPE_ID = PRODUCT.RECIPE_ID 
WHERE PRODUCT.ware = 'Drinking water' 
ORDER BY MANUFACTURER.company ASC;


