SELECT DISTINCT p.WARE
FROM PRODUCT p
WHERE NOT EXISTS (
    SELECT 1
    FROM MATERIAL m
    JOIN CATEGORY c ON m.WARE = c.WARE
    WHERE m.RECIPE_ID = p.RECIPE_ID
    AND c.CLASS != 'Mineral'
)
ORDER BY p.WARE ASC;