SELECT DISTINCT m.COMPANY
FROM MANUFACTURER m
JOIN PRODUCT p ON m.RECIPE_ID = p.RECIPE_ID
JOIN CATEGORY c ON p.WARE = c.WARE
WHERE c.CLASS IN (
    SELECT c2.CLASS
    FROM CATEGORY c2
    JOIN PRODUCT p2 ON c2.WARE = p2.WARE
    JOIN MANUFACTURER m2 ON p2.RECIPE_ID = m2.RECIPE_ID
    WHERE m2.COMPANY = m.COMPANY
    GROUP BY c2.CLASS
    HAVING COUNT(DISTINCT p2.WARE) >= 2
)
ORDER BY m.COMPANY ASC;
