SELECT DISTINCT m1.COMPANY
FROM PRODUCT p1
JOIN MATERIAL m ON p1.WARE = m.WARE
JOIN PRODUCT p2 ON m.RECIPE_ID = p2.RECIPE_ID
JOIN MANUFACTURER m1 ON p1.RECIPE_ID = m1.RECIPE_ID
JOIN MANUFACTURER m2 ON p2.RECIPE_ID = m2.RECIPE_ID
WHERE m1.COMPANY = m2.COMPANY
ORDER BY m1.COMPANY ASC;
