SELECT MANUFACTURER.COMPANY
FROM PRODUCT
JOIN MANUFACTURER ON MANUFACTURER.RECIPE_ID = PRODUCT.RECIPE_ID
JOIN CATEGORY ON PRODUCT.ware = CATEGORY.ware
WHERE CATEGORY.CLASS = 'Fuel'

INTERSECT

SELECT MANUFACTURER.COMPANY
FROM PRODUCT
JOIN MANUFACTURER ON MANUFACTURER.RECIPE_ID = PRODUCT.RECIPE_ID
JOIN CATEGORY ON PRODUCT.ware = CATEGORY.ware
WHERE CATEGORY.CLASS = 'Food';
